spring.application.name=news-parser-service
spring.datasource.url=jdbc:mysql://localhost:3313/business_sustainability
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.defer-datasource-initialization=true
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.initialization-fail-timeout=60000
spring.datasource.hikari.maximum-pool-size=10

server.port=8080

yandex.translate.url=https://translate.api.cloud.yandex.net/translate/v2/translate
yandex.translate.folder-id=b1gp1g2mdlpi2c1hhmv4
yandex.translate.api-key=AQVN3-a6J8IzFAX3EsxLnZgsQFrrhMjFVSlG_ES4

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true