# Generated by Django 5.2.6 on 2026-05-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceclient',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='serviceclient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='serviceclient',
            name='api_key',
            field=models.CharField(db_index=True, editable=False, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='serviceclient',
            name='scopes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterModelTable(
            name='serviceclient',
            table='service_clients',
        ),
    ]
