# Generated by Django 5.2.6 on 2026-04-19 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'general_question',
            },
        ),
        migrations.CreateModel(
            name='SDGGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'sdg_goal',
            },
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_options', to='portal.generalquestion')),
            ],
            options={
                'db_table': 'answer_option',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('organization_name', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SDGQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('sdg_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='portal.sdggoal')),
            ],
            options={
                'db_table': 'sdg_question',
            },
        ),
        migrations.CreateModel(
            name='AnswerOptionTranslation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=5)),
                ('text', models.TextField()),
                ('answer_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='portal.answeroption')),
            ],
            options={
                'db_table': 'answer_option_translation',
                'unique_together': {('answer_option', 'language')},
            },
        ),
        migrations.CreateModel(
            name='GeneralQuestionTranslation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=5)),
                ('text', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='portal.generalquestion')),
            ],
            options={
                'db_table': 'general_question_translation',
                'unique_together': {('question', 'language')},
            },
        ),
        migrations.CreateModel(
            name='SDGQuestionTranslation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=5)),
                ('text', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='portal.sdgquestion')),
            ],
            options={
                'db_table': 'sdg_question_translation',
                'unique_together': {('question', 'language')},
            },
        ),
    ]
