# Generated by Django 5.2.6 on 2026-05-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_questionnairesubmission_questionnaireanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnairesubmission',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20),
        ),
    ]
