# Generated by Django 5.2.6 on 2026-05-15 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_questionnairesubmission_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireAnswerResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='portal.questionnairesubmission')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionnaireChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labels', models.JSONField()),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chart', to='portal.questionnairesubmission')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionnaireChartSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdg_code', models.IntegerField()),
                ('scenario', models.IntegerField()),
                ('label', models.CharField(max_length=255)),
                ('start_value', models.FloatField()),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='portal.questionnairechart')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionnaireChartPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='portal.questionnairechartseries')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionnaireNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.TextField()),
                ('pestel_type', models.CharField(max_length=50)),
                ('impact_type', models.CharField(max_length=50)),
                ('impact_strength', models.FloatField()),
                ('url', models.URLField()),
                ('title_en', models.TextField()),
                ('title_kz', models.TextField()),
                ('sdg', models.JSONField()),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='portal.questionnairesubmission')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionnaireRecommendedSDG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdg_number', models.IntegerField()),
                ('current_value', models.FloatField()),
                ('recommended_value', models.FloatField()),
                ('delta', models.FloatField()),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_sdgs', to='portal.questionnairesubmission')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionnaireResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField()),
                ('sdg_number', models.IntegerField()),
                ('value', models.FloatField()),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='portal.questionnairesubmission')),
            ],
        ),
    ]
