# Generated by Django 5.2.6 on 2026-05-15 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_questionnaireanswerresult_questionnairechart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaireresult',
            name='company_id',
        ),
    ]
