# Generated by Django 5.2.6 on 2026-05-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_remove_questionnaireresult_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='mailing',
            field=models.BooleanField(default=False),
        ),
    ]
