# Generated by Django 5.2.6 on 2026-05-23 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_organization_mailing'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=128)),
                ('value', models.FloatField()),
                ('sdg_numbers', models.JSONField()),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='portal.questionnairesubmission')),
            ],
            options={
                'db_table': 'questionnaire_category',
            },
        ),
    ]
