# Generated by Django 5.2.6 on 2026-05-23 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_questionnairecategory'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='questionnaireanswerresult',
            table='questionnaire_answer_result',
        ),
        migrations.AlterModelTable(
            name='questionnairechart',
            table='questionnaire_chart',
        ),
        migrations.AlterModelTable(
            name='questionnairechartpoint',
            table='questionnaire_chart_point',
        ),
        migrations.AlterModelTable(
            name='questionnairechartseries',
            table='questionnaire_chart_series',
        ),
        migrations.AlterModelTable(
            name='questionnairenews',
            table='questionnaire_news',
        ),
        migrations.AlterModelTable(
            name='questionnairerecommendedsdg',
            table='questionnaire_recommended_sdg',
        ),
        migrations.AlterModelTable(
            name='questionnaireresult',
            table='questionnaire_result',
        ),
        migrations.AlterModelTable(
            name='questionnairesubmission',
            table='questionnaire_submission',
        ),
    ]
