# Generated by Django 5.2.6 on 2025-10-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='cur',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
