 # Generated by Django 5.2.7 on 2025-10-27 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portal', '0002_alter_questionnaire_cur'),
    ]

    operations = [
        migrations.CreateModel(
            name='SDGGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'sdg_goal',
            },
        ),

        # --- SDG Questions ---
        migrations.CreateModel(
            name='SDGQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('sdg_goal', models.ForeignKey(
                    null=True,
                    db_column='sdg_id',
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='sdg_questions',
                    to='portal.SDGGoal'
                )),
            ],
            options={
                'db_table': 'sdg_question',
            },
        ),

        # --- General Questions ---
        migrations.CreateModel(
            name='GeneralQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'general_question',
            },
        ),

        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                # ('score', models.DecimalField(max_digits=3, decimal_places=2, null=True, blank=True)),
                ('question', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='answer_options',
                    to='portal.generalquestion'
                )),
            ],
            options={
                'db_table': 'answer_option',
            },
        ),

        # --- AnswerOption Translation ---
        migrations.CreateModel(
            name='AnswerOptionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=5)),
                ('text', models.TextField()),
                ('answer_option', models.ForeignKey(
                    on_delete=models.CASCADE,
                    related_name='translations',
                    to='portal.answeroption'
                )),
            ],
            options={
                'db_table': 'answer_option_translation',
                'unique_together': {('answer_option', 'language')},
            },
        ),

        # --- SDG Question Translation ---
        migrations.CreateModel(
            name='SDGQuestionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=5)),
                ('text', models.TextField()),
                ('question', models.ForeignKey(
                    on_delete=models.CASCADE,
                    related_name='translations',
                    to='portal.sdgquestion'
                )),
            ],
            options={
                'db_table': 'sdg_question_translation',
                'unique_together': {('question', 'language')},
            },
        ),

        # --- General Question Translation ---
        migrations.CreateModel(
            name='GeneralQuestionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=5)),
                ('text', models.TextField()),
                ('question', models.ForeignKey(
                    on_delete=models.CASCADE,
                    related_name='translations',
                    to='portal.generalquestion'
                )),
            ],
            options={
                'db_table': 'general_question_translation',
                'unique_together': {('question', 'language')},
            },
        ),


    ]
