# Generated by Django 5.2.7 on 2026-03-07 11:47

from django.db import migrations


def seed_data(apps, schema_editor):

    SDGGoal = apps.get_model('portal', 'SDGGoal')
    SDGQuestion = apps.get_model('portal', 'SDGQuestion')
    GeneralQuestion = apps.get_model('portal', 'GeneralQuestion')
    AnswerOption = apps.get_model('portal', 'AnswerOption')
    AnswerOptionTranslation = apps.get_model('portal', 'AnswerOptionTranslation')
    SDGQuestionTranslation = apps.get_model('portal', 'SDGQuestionTranslation')
    GeneralQuestionTranslation = apps.get_model('portal', 'GeneralQuestionTranslation')

    # -------------------------
    # SDG GOALS
    # -------------------------

    goals = [
        {"id": 1, "number": 1, "title": "Ликвидация бедности"},
        {"id": 2, "number": 3, "title": "Здоровье и благополучие"},
        {"id": 3, "number": 4, "title": "Качественное образование"},
        {"id": 4, "number": 5, "title": "Гендерное равенство"},
        {"id": 5, "number": 6, "title": "Чистая вода и санитария"},
        {"id": 6, "number": 7, "title": "Доступная и чистая энергия"},
        {"id": 7, "number": 8, "title": "Достойная работа и экономический рост"},
        {"id": 8, "number": 9, "title": "Индустриализация, инновации и инфраструктура"},
        {"id": 9, "number": 10, "title": "Уменьшение неравенства"},
        {"id": 10, "number": 12, "title": "Ответственное потребление и производство"},
        {"id": 11, "number": 13, "title": "Борьба с изменением климата"},
        {"id": 12, "number": 15, "title": "Сохранение экосистем суши"},
        {"id": 13, "number": 16, "title": "Мир, правосудие и эффективные институты"},
        {"id": 14, "number": 17, "title": "Партнёрство в интересах устойчивого развития"},
    ]

    for g in goals:
        SDGGoal.objects.update_or_create(
            id=g["id"],
            defaults=g
        )

    # -------------------------
    # SDG ANSWER TEMPLATE
    # -------------------------

    # sdg_answers = [
    #     {"id": 1, "text": "Полностью реализовано", "score": 1.0, "type": "SDG",
    #      "translations": {"ru": "Полностью реализовано", "en": "Fully implemented", "kz": "Толық жүзеге асырылған"}},
    #     {"id": 2, "text": "Реализовано в значительной степени", "score": 0.8, "type": "SDG",
    #      "translations": {"ru": "Реализовано в значительной степени", "en": "Largely implemented",
    #                       "kz": "Елеулі түрде жүзеге асырылған"}},
    #     {"id": 3, "text": "Частично реализовано", "score": 0.5, "type": "SDG",
    #      "translations": {"ru": "Частично реализовано", "en": "Partially implemented",
    #                       "kz": "Жартылай жүзеге асырылған"}},
    #     {"id": 4, "text": "На начальной стадии внедрения", "score": 0.2, "type": "SDG",
    #      "translations": {"ru": "На начальной стадии внедрения", "en": "At initial stage", "kz": "Бастапқы кезеңде"}},
    #     {"id": 5, "text": "Не реализовано", "score": 0.0, "type": "SDG",
    #      "translations": {"ru": "Не реализовано", "en": "Not implemented", "kz": "Жүзеге асырылмаған"}},
    # ]
    #
    # for a in sdg_answers:
    #     obj, created = AnswerOption.objects.update_or_create(
    #         id=a["id"],
    #         defaults={k: v for k, v in a.items() if k != "translations"}
    #     )
    #     if "translations" in a:
    #         for lang, text in a["translations"].items():
    #             AnswerOptionTranslation.objects.update_or_create(
    #                 answer_option=obj,
    #                 language=lang,
    #                 defaults={"text": text}
    #             )

    # for option_data in sdg_answers:
    #     option, created = AnswerOption.objects.get_or_create(
    #         # code=option_data["code"],
    #         defaults={"score": option_data["score"], "type": option_data["type"]}
    #     )
    #     if "translations" in option_data:
    #         for lang, text in option_data["translations"].items():
    #             AnswerOptionTranslation.objects.update_or_create(
    #                 answer_option=option,
    #                 language=lang,
    #                 defaults={"text": text}
    #             )



    # -------------------------
    # QUESTIONS
    # -------------------------

    sdg_questions = [

        # ---------- SDG 1 ----------
        {"id": 1,
         "text": "Насколько в компании реализована политика обеспечения оплаты труда на уровне не ниже прожиточного минимума?",
         "sdg_goal_id": 1,
         "translations": {
             "ru": "Насколько в компании реализована политика обеспечения оплаты труда на уровне не ниже прожиточного минимума?",
             "en": "To what extent does the company ensure wages are not below the subsistence minimum?",
             "kz": "Компанияда ең төменгі күнкөріс деңгейінен төмен емес еңбекақыны қамтамасыз ету саясаты қаншалықты жүзеге асырылған?"
         }},

        {"id": 2,
         "text": "В какой степени в компании внедрена система социальных льгот для сотрудников?",
         "sdg_goal_id": 1,
         "translations": {
             "ru": "В какой степени в компании внедрена система социальных льгот для сотрудников?",
             "en": "To what extent has a system of employee social benefits been implemented?",
             "kz": "Компанияда қызметкерлерге арналған әлеуметтік жеңілдіктер жүйесі қаншалықты енгізілген?"
         }},

        {"id": 3,
         "text": "Насколько системно компания реализует программы поддержки уязвимых групп населения?",
         "sdg_goal_id": 1,
         "translations": {
             "ru": "Насколько системно компания реализует программы поддержки уязвимых групп населения?",
             "en": "How systematically does the company implement programs to support vulnerable groups?",
             "kz": "Компания осал топтарды қолдау бағдарламаларын қаншалықты жүйелі түрде жүзеге асырады?"
         }},

        {"id": 4,
         "text": "Насколько в компании обеспечен достойный уровень средней заработной платы сотрудников?",
         "sdg_goal_id": 1,
         "translations": {
             "ru": "Насколько в компании обеспечен достойный уровень средней заработной платы сотрудников?",
             "en": "To what extent does the company ensure a decent average salary level?",
             "kz": "Компанияда қызметкерлердің орташа жалақысының лайықты деңгейі қаншалықты қамтамасыз етілген?"
         }},

        # ---------- SDG 3 ----------
        {"id": 5,
         "text": "Насколько в компании обеспечены безопасные и здоровые условия труда?",
         "sdg_goal_id": 2,
         "translations": {
             "ru": "Насколько в компании обеспечены безопасные и здоровые условия труда?",
             "en": "To what extent are safe and healthy working conditions ensured?",
             "kz": "Компанияда қауіпсіз және салауатты еңбек жағдайлары қаншалықты қамтамасыз етілген?"
         }},

        {"id": 6,
         "text": "В какой степени внедрена система медицинского страхования сотрудников?",
         "sdg_goal_id": 2,
         "translations": {
             "ru": "В какой степени внедрена система медицинского страхования сотрудников?",
             "en": "To what extent has employee health insurance been implemented?",
             "kz": "Қызметкерлерді медициналық сақтандыру жүйесі қаншалықты енгізілген?"
         }},

        {"id": 7,
         "text": "Насколько реализуются программы поддержания здоровья работников?",
         "sdg_goal_id": 2,
         "translations": {
             "ru": "Насколько реализуются программы поддержания здоровья работников?",
             "en": "How effectively are employee health programs implemented?",
             "kz": "Қызметкерлердің денсаулығын қолдау бағдарламалары қаншалықты жүзеге асырылуда?"
         }},

        {"id": 8,
         "text": "В какой степени сотрудники проходили обучение или повышение квалификации за последний год?",
         "sdg_goal_id": 2,
         "translations": {
             "ru": "В какой степени сотрудники проходили обучение или повышение квалификации за последний год?",
             "en": "To what extent have employees undergone training or professional development over the past year?",
             "kz": "Соңғы жылда қызметкерлер оқудан немесе біліктілігін арттырудан қаншалықты өтті?"
         }},

        # ---------- SDG 4 ----------
        {"id": 9,
         "text": "Насколько в компании реализована система поддержки обучения сотрудников?",
         "sdg_goal_id": 3,
         "translations": {
             "ru": "Насколько в компании реализована система поддержки обучения сотрудников?",
             "en": "To what extent is an employee training support system implemented?",
             "kz": "Компанияда қызметкерлерді оқытуды қолдау жүйесі қаншалықты жүзеге асырылған?"
         }},

        {"id": 10,
         "text": "В какой степени компания участвует в подготовке кадров через стажировки?",
         "sdg_goal_id": 3,
         "translations": {
             "ru": "В какой степени компания участвует в подготовке кадров через стажировки?",
             "en": "To what extent does the company participate in workforce training through internships?",
             "kz": "Компания кадрларды даярлауға тағылымдамалар арқылы қаншалықты қатысады?"
         }},

        {"id": 11,
         "text": "Насколько компания вовлечена в образовательные инициативы?",
         "sdg_goal_id": 3,
         "translations": {
             "ru": "Насколько компания вовлечена в образовательные инициативы?",
             "en": "How involved is the company in educational initiatives?",
             "kz": "Компания білім беру бастамаларына қаншалықты қатысады?"
         }},

        {"id": 12,
         "text": "В какой степени сотрудники охвачены обучением за последний год?",
         "sdg_goal_id": 3,
         "translations": {
             "ru": "В какой степени сотрудники охвачены обучением за последний год?",
             "en": "To what extent have employees been covered by training over the past year?",
             "kz": "Соңғы жылда қызметкерлер оқумен қаншалықты қамтылды?"
         }},

        # ---------- SDG 5 ----------
        {"id": 13,
         "text": "Насколько в компании обеспечен сбалансированный гендерный состав сотрудников?",
         "sdg_goal_id": 4,
         "translations": {
             "ru": "Насколько в компании обеспечен сбалансированный гендерный состав сотрудников?",
             "en": "To what extent is gender balance ensured among employees?",
             "kz": "Компанияда қызметкерлердің гендерлік теңгерімі қаншалықты қамтамасыз етілген?"
         }},

        {"id": 14,
         "text": "В какой степени женщины представлены в руководящих должностях?",
         "sdg_goal_id": 4,
         "translations": {
             "ru": "В какой степени женщины представлены в руководящих должностях?",
             "en": "To what extent are women represented in leadership positions?",
             "kz": "Әйелдер басшылық лауазымдарда қаншалықты ұсынылған?"
         }},

        {"id": 15,
         "text": "Насколько реализован принцип равной оплаты труда мужчин и женщин?",
         "sdg_goal_id": 4,
         "translations": {
             "ru": "Насколько реализован принцип равной оплаты труда мужчин и женщин?",
             "en": "To what extent is the principle of equal pay for men and women implemented?",
             "kz": "Ерлер мен әйелдерге тең еңбекақы төлеу қағидаты қаншалықты жүзеге асырылған?"
         }},

        {"id": 16,
         "text": "В какой степени внедрены программы поддержки и развития женщин?",
         "sdg_goal_id": 4,
         "translations": {
             "ru": "В какой степени внедрены программы поддержки и развития женщин?",
             "en": "To what extent are programs for women's support and development implemented?",
             "kz": "Әйелдерді қолдау және дамыту бағдарламалары қаншалықты енгізілген?"
         }},

        # ---------- SDG 6 ----------
        {"id": 17, "text": "Насколько внедрены технологии экономного использования воды?",
         "sdg_goal_id": 5,
         "translations": {
             "ru": "Насколько внедрены технологии экономного использования воды?",
             "en": "To what extent are water-saving technologies implemented?",
             "kz": "Суды үнемдеу технологиялары қаншалықты енгізілген?"
         }},
        {"id": 18, "text": "В какой степени организован контроль качества воды?", "sdg_goal_id": 5,
         "translations": {
             "ru": "В какой степени организован контроль качества воды?",
             "en": "To what extent is water quality control organized?",
             "kz": "Су сапасын бақылау қаншалықты ұйымдастырылған?"
         }},
        {"id": 19, "text": "Насколько компания участвует в инициативах по защите водных ресурсов?",
         "sdg_goal_id": 5,
         "translations": {
             "ru": "Насколько компания участвует в инициативах по защите водных ресурсов?",
             "en": "To what extent does the company participate in water resource protection initiatives?",
             "kz": "Компания су ресурстарын қорғау бастамаларына қаншалықты қатысады?"
         }},
        {"id": 20, "text": "В какой степени оптимизировано потребление водных ресурсов?",
         "sdg_goal_id": 5,
         "translations": {
             "ru": "В какой степени оптимизировано потребление водных ресурсов?",
             "en": "To what extent is water consumption optimized?",
             "kz": "Су ресурстарын тұтыну қаншалықты оңтайландырылған?"
         }},

        # ---------- SDG 7 ----------
        {"id": 21, "text": "В какой степени компания использует возобновляемые источники энергии?",
         "sdg_goal_id": 6,
         "translations": {
             "ru": "В какой степени компания использует возобновляемые источники энергии?",
             "en": "To what extent does the company use renewable energy sources?",
             "kz": "Компания жаңартылатын энергия көздерін қаншалықты пайдаланады?"
         }},
        {"id": 22, "text": "Насколько широко внедрены энергоэффективные технологии?",
         "sdg_goal_id": 6,
         "translations": {
             "ru": "Насколько широко внедрены энергоэффективные технологии?",
             "en": "How widely are energy-efficient technologies implemented?",
             "kz": "Энергия тиімді технологиялар қаншалықты кең енгізілген?"
         }},
        {"id": 23, "text": "В какой степени компания оценивает углеродный след?", "sdg_goal_id": 6,
         "translations": {
             "ru": "В какой степени компания оценивает углеродный след?",
             "en": "To what extent does the company assess its carbon footprint?",
             "kz": "Компания көміртек ізін қаншалықты бағалайды?"
         }},
        {"id": 24, "text": "Насколько компании удалось сократить энергозатраты?", "sdg_goal_id": 6,
         "translations": {
             "ru": "Насколько компании удалось сократить энергозатраты?",
             "en": "To what extent has the company reduced energy consumption?",
             "kz": "Компания энергия шығындарын қаншалықты қысқартты?"
         }},

        # ---------- SDG 8 ----------
        {"id": 25, "text": "Насколько обеспечена стабильная и достойная занятость сотрудников?",
         "sdg_goal_id": 7,
         "translations": {
             "ru": "Насколько обеспечена стабильная и достойная занятость сотрудников?",
             "en": "To what extent is stable and decent employment ensured?",
             "kz": "Қызметкерлердің тұрақты және лайықты жұмыспен қамтылуы қаншалықты қамтамасыз етілген?"
         }},
        {"id": 26, "text": "В какой степени применяются современные методы повышения производительности?",
         "sdg_goal_id": 7,
         "translations": {
             "ru": "В какой степени применяются современные методы повышения производительности?",
             "en": "To what extent are modern productivity improvement methods applied?",
             "kz": "Өнімділікті арттырудың заманауи әдістері қаншалықты қолданылады?"
         }},
        {"id": 27, "text": "Насколько в компании преобладает постоянная форма занятости?",
         "sdg_goal_id": 7,
         "translations": {
             "ru": "Насколько в компании преобладает постоянная форма занятости?",
             "en": "To what extent does permanent employment prevail in the company?",
             "kz": "Компанияда тұрақты жұмыспен қамту қаншалықты басым?"
         }},
        {"id": 28, "text": "В какой степени созданы условия для карьерного роста сотрудников?",
         "sdg_goal_id": 7,
         "translations": {
             "ru": "В какой степени созданы условия для карьерного роста сотрудников?",
             "en": "To what extent are conditions for career growth provided?",
             "kz": "Қызметкерлердің мансаптық өсуіне жағдай қаншалықты жасалған?"
         }},

        # ---------- SDG 9 ----------
        {"id": 29, "text": "Насколько компания инвестирует в инновации и технологии?",
         "sdg_goal_id": 8,
         "translations": {
             "ru": "Насколько компания инвестирует в инновации и технологии?",
             "en": "To what extent does the company invest in innovation and technology?",
             "kz": "Компания инновациялар мен технологияларға қаншалықты инвестиция салады?"
         }},
        {"id": 30, "text": "В какой степени внедрены цифровые инструменты управления?",
         "sdg_goal_id": 8,
         "translations": {
             "ru": "В какой степени внедрены цифровые инструменты управления?",
             "en": "To what extent are digital management tools implemented?",
             "kz": "Цифрлық басқару құралдары қаншалықты енгізілген?"
         }},
        {"id": 31, "text": "Насколько компания вовлечена в партнёрские инновационные проекты?",
         "sdg_goal_id": 8,
         "translations": {
             "ru": "Насколько компания вовлечена в партнёрские инновационные проекты?",
             "en": "To what extent is the company involved in partnership innovation projects?",
             "kz": "Компания серіктестік инновациялық жобаларға қаншалықты қатысады?"
         }},
        {"id": 32, "text": "В какой степени доход компании направляется на инновации и R&D?",
         "sdg_goal_id": 8,
         "translations": {
             "ru": "В какой степени доход компании направляется на инновации и R&D?",
             "en": "To what extent is company revenue allocated to innovation and R&D?",
             "kz": "Компания табысының қаншалықты бөлігі инновациялар мен ҒЗТКЖ-ға бағытталады?"
         }},

        # ---------- SDG 10 ----------
        {"id": 33, "text": "Насколько обеспечены равные возможности трудоустройства?",
         "sdg_goal_id": 9,
         "translations": {
             "ru": "Насколько обеспечены равные возможности трудоустройства?",
             "en": "To what extent are equal employment opportunities ensured?",
             "kz": "Жұмыспен қамтудың тең мүмкіндіктері қаншалықты қамтамасыз етілген?"
         }},
        {"id": 34, "text": "В какой степени компания вовлекает уязвимые группы населения?",
         "sdg_goal_id": 9,
         "translations": {
             "ru": "В какой степени компания вовлекает уязвимые группы населения?",
             "en": "To what extent does the company engage vulnerable groups?",
             "kz": "Компания осал топтарды қаншалықты тартады?"
         }},
        {"id": 35, "text": "Насколько компания участвует в программах поддержки уязвимых групп?",
         "sdg_goal_id": 9,
         "translations": {
             "ru": "Насколько компания участвует в программах поддержки уязвимых групп?",
             "en": "To what extent does the company participate in support programs for vulnerable groups?",
             "kz": "Компания осал топтарды қолдау бағдарламаларына қаншалықты қатысады?"
         }},
        {"id": 36, "text": "В какой степени обеспечен равный доступ к обучению и карьерному росту?",
         "sdg_goal_id": 9,
         "translations": {
             "ru": "В какой степени обеспечен равный доступ к обучению и карьерному росту?",
             "en": "To what extent is equal access to training and career growth ensured?",
             "kz": "Оқыту мен мансаптық өсуге тең қолжетімділік қаншалықты қамтамасыз етілген?"
         }},

        # ---------- SDG 12 ----------
        {"id": 37, "text": "Насколько эффективно организовано управление отходами?",
         "sdg_goal_id": 10,
         "translations": {
             "ru": "Насколько эффективно организовано управление отходами?",
             "en": "How effectively is waste management organized?",
             "kz": "Қалдықтарды басқару қаншалықты тиімді ұйымдастырылған?"
         }},
        {"id": 38, "text": "В какой степени применяются принципы зелёного производства?",
         "sdg_goal_id": 10,
         "translations": {
             "ru": "В какой степени применяются принципы зелёного производства?",
             "en": "To what extent are green production principles applied?",
             "kz": "Жасыл өндіріс қағидаттары қаншалықты қолданылады?"
         }},
        {"id": 39, "text": "Насколько внедрена система контроля жизненного цикла продукции?",
         "sdg_goal_id": 10,
         "translations": {
             "ru": "Насколько внедрена система контроля жизненного цикла продукции?",
             "en": "To what extent is product lifecycle management implemented?",
             "kz": "Өнімнің өмірлік циклін басқару жүйесі қаншалықты енгізілген?"
         }},
        {"id": 40, "text": "В какой степени обеспечивается переработка отходов?",
         "sdg_goal_id": 10,
         "translations": {
             "ru": "В какой степени обеспечивается переработка отходов?",
             "en": "To what extent is waste recycling ensured?",
             "kz": "Қалдықтарды қайта өңдеу қаншалықты қамтамасыз етілген?"
         }},

        # ---------- SDG 13 ----------
        {"id": 41, "text": "Насколько реализована практика оценки выбросов парниковых газов?",
         "sdg_goal_id": 11,
         "translations": {
             "ru": "Насколько реализована практика оценки выбросов парниковых газов?",
             "en": "To what extent are greenhouse gas emissions assessed?",
             "kz": "Парниктік газдар шығарындыларын бағалау қаншалықты жүзеге асырылады?"
         }},
        {"id": 42, "text": "В какой степени внедряются меры по снижению углеродного следа?",
         "sdg_goal_id": 11,
         "translations": {
             "ru": "В какой степени внедряются меры по снижению углеродного следа?",
             "en": "To what extent are measures to reduce the carbon footprint implemented?",
             "kz": "Көміртек ізін азайту шаралары қаншалықты енгізілуде?"
         }},
        {"id": 43, "text": "Насколько системно сотрудники обучаются экологической ответственности?",
         "sdg_goal_id": 11,
         "translations": {
             "ru": "Насколько системно сотрудники обучаются экологической ответственности?",
             "en": "To what extent are employees systematically trained in environmental responsibility?",
             "kz": "Қызметкерлер экологиялық жауапкершілікке қаншалықты жүйелі түрде оқытылады?"
         }},
        {"id": 44, "text": "В какой степени компании удалось сократить выбросы CO2?",
         "sdg_goal_id": 11,
         "translations": {
             "ru": "В какой степени компании удалось сократить выбросы CO2?",
             "en": "To what extent has the company reduced CO2 emissions?",
             "kz": "Компания CO₂ шығарындыларын қаншалықты қысқартты?"
         }},

        # ---------- SDG 15 ----------
        {"id": 45, "text": "Насколько деятельность компании влияет на природные ресурсы?",
         "sdg_goal_id": 12,
         "translations": {
             "ru": "Насколько деятельность компании влияет на природные ресурсы?",
             "en": "To what extent does the company’s activity impact natural resources?",
             "kz": "Компания қызметі табиғи ресурстарға қаншалықты әсер етеді?"
         }},
        {"id": 46, "text": "В какой степени реализуются программы восстановления экосистем?",
         "sdg_goal_id": 12,
         "translations": {
             "ru": "В какой степени реализуются программы восстановления экосистем?",
             "en": "To what extent are ecosystem restoration programs implemented?",
             "kz": "Экожүйелерді қалпына келтіру бағдарламалары қаншалықты жүзеге асырылады?"
         }},
        {"id": 47, "text": "Насколько сформирована стратегия ответственного использования земель?",
         "sdg_goal_id": 12,
         "translations": {
             "ru": "Насколько сформирована стратегия ответственного использования земель?",
             "en": "To what extent is a responsible land use strategy developed?",
             "kz": "Жер ресурстарын жауапты пайдалану стратегиясы қаншалықты қалыптасқан?"
         }},
        {"id": 48, "text": "В какой степени компания участвует в озеленении и восстановлении среды?",
         "sdg_goal_id": 12,
         "translations": {
             "ru": "В какой степени компания участвует в озеленении и восстановлении среды?",
             "en": "To what extent does the company participate in greening and environmental restoration?",
             "kz": "Компания көгалдандыру және қоршаған ортаны қалпына келтіруге қаншалықты қатысады?"
         }},

        # ---------- SDG 16 ----------
        {"id": 49, "text": "Насколько внедрена политика антикоррупции и прозрачности?",
         "sdg_goal_id": 13,
         "translations": {
             "ru": "Насколько внедрена политика антикоррупции и прозрачности?",
             "en": "To what extent are anti-corruption and transparency policies implemented?",
             "kz": "Сыбайлас жемқорлыққа қарсы және ашықтық саясаты қаншалықты енгізілген?"
         }},
        {"id": 50, "text": "В какой степени компания обеспечивает защиту прав сотрудников и клиентов?",
         "sdg_goal_id": 13,
         "translations": {
             "ru": "В какой степени компания обеспечивает защиту прав сотрудников и клиентов?",
             "en": "To what extent does the company ensure the protection of employee and client rights?",
             "kz": "Компания қызметкерлер мен клиенттердің құқықтарын қаншалықты қорғайды?"
         }},
        {"id": 51, "text": "Насколько эффективно работают механизмы обратной связи?",
         "sdg_goal_id": 13,
         "translations": {
             "ru": "Насколько эффективно работают механизмы обратной связи?",
             "en": "How effective are feedback mechanisms?",
             "kz": "Кері байланыс механизмдері қаншалықты тиімді жұмыс істейді?"
         }},
        {"id": 52, "text": "В какой степени сотрудники обучены вопросам этики и антикоррупции?",
         "sdg_goal_id": 13,
         "translations": {
             "ru": "В какой степени сотрудники обучены вопросам этики и антикоррупции?",
             "en": "To what extent are employees trained in ethics and anti-corruption?",
             "kz": "Қызметкерлер этика және сыбайлас жемқорлыққа қарсы мәселелер бойынша қаншалықты оқытылған?"
         }},

        # ---------- SDG 17 ----------
        {"id": 53, "text": "Насколько активно компания участвует в партнёрских проектах устойчивого развития?",
         "sdg_goal_id": 14,
         "translations": {
             "ru": "Насколько активно компания участвует в партнёрских проектах устойчивого развития?",
             "en": "How actively does the company participate in sustainable development partnerships?",
             "kz": "Компания тұрақты даму бойынша серіктестік жобаларға қаншалықты белсенді қатысады?"
         }},
        {"id": 54, "text": "В какой степени компания делится опытом и практиками?",
         "sdg_goal_id": 14,
         "translations": {
             "ru": "В какой степени компания делится опытом и практиками?",
             "en": "To what extent does the company share experience and best practices?",
             "kz": "Компания тәжірибе мен үздік практикаларды қаншалықты бөліседі?"
         }},
        {"id": 55, "text": "Насколько компания привлекает внешние инвестиции для устойчивых инициатив?",
         "sdg_goal_id": 14,
         "translations": {
             "ru": "Насколько компания привлекает внешние инвестиции для устойчивых инициатив?",
             "en": "To what extent does the company attract external investments for sustainable initiatives?",
             "kz": "Компания тұрақты бастамалар үшін сыртқы инвестицияларды қаншалықты тартады?"
         }},
        {"id": 56, "text": "В какой степени проекты реализуются совместно с другими организациями?",
         "sdg_goal_id": 14,
         "translations": {
             "ru": "В какой степени проекты реализуются совместно с другими организациями?",
             "en": "To what extent are projects implemented in collaboration with other organizations?",
             "kz": "Жобалар басқа ұйымдармен бірлесіп қаншалықты жүзеге асырылады?"
         }},
    ]

    for q in sdg_questions:
        obj, _ = SDGQuestion.objects.update_or_create(
            id=q["id"],
            defaults={
                "text": q["text"],
                "active": True,
                "sdg_goal_id": q["sdg_goal_id"]
            }
        )

        for lang, text in q["translations"].items():
            SDGQuestionTranslation.objects.update_or_create(
                question=obj,
                language=lang,
                defaults={"text": text}
            )

    general_questions = [
        # ---------- Общие вопросы ----------
        {"id": 1,
         "text": "Укажите среднюю численность сотрудников в вашей компании.", "sdg_goal_id": None,
         "translations": {
             "ru": "Укажите среднюю численность сотрудников в вашей компании.",
             "en": "Indicate the average number of employees in your company.",
             "kz": "Компанияңыздағы қызметкерлердің орташа санын көрсетіңіз:"
         }},

        {"id": 2,
         "text": "Укажите основной вид деятельности вашей компании.", "sdg_goal_id": None,
         "translations": {
             "ru": "Укажите основной вид деятельности вашей компании.",
             "en": "Indicate the main activity of your company.",
             "kz": "Компанияңыздың негізгі қызмет түрін көрсетіңіз:"
         }},

        {"id": 3,
         "text": "Укажите организационно-правовую форму вашей компании.", "sdg_goal_id": None,
         "translations": {
             "ru": "Укажите организационно-правовую форму вашей компании.",
             "en": "Indicate the legal form of your company.",
             "kz": "Компанияңыздың ұйымдық-құқықтық нысанын көрсетіңіз:"
         }},

        {"id": 4,
         "text": "Осуществляет ли компания собственные производственные процессы?", "sdg_goal_id": None,
         "translations": {
             "ru": "Осуществляет ли компания собственные производственные процессы?",
             "en": "Does the company carry out its own production processes?",
             "kz": "Компания өз өндірістік процестерін жүзеге асыра ма?"
         }},

        {"id": 5,
         "text": "Использует ли компания значительные объёмы природных ресурсов?", "sdg_goal_id": None,
         "translations": {
             "ru": "Использует ли компания значительные объёмы природных ресурсов?",
             "en": "Does the company use significant amounts of natural resources?",
             "kz": "Компания табиғи ресурстарды айтарлықтай көлемде пайдалана ма?"
         }},

        {"id": 6,
         "text": "Участвует ли компания в государственных или международных программах поддержки / развития?", "sdg_goal_id": None,
         "translations": {
             "ru": "Участвует ли компания в государственных или международных программах поддержки / развития?",
             "en": "Does the company participate in national or international support/development programs?",
             "kz": "Компания мемлекеттік немесе халықаралық қолдау/даму бағдарламаларына қатыса ма?"
         }},

        {"id": 7,
         "text": "Кто является основной целевой аудиторией вашей компании?", "sdg_goal_id": None,
         "translations": {
             "ru": "Кто является основной целевой аудиторией вашей компании?",
             "en": "Who is the main target audience of your company?",
             "kz": "Компанияңыздың негізгі мақсатты аудиториясы кім?"
         }},

        {"id": 8,
         "text": "Есть ли у компании собственное помещение?", "sdg_goal_id": None,
         "translations": {
             "ru": "Есть ли у компании собственное помещение?",
             "en": "Does the company have its own premises?",
             "kz": "Компанияның өз ғимараты бар ма?"
         }},

        {"id": 9,
         "text": "Существует ли значительная сезонность бизнеса?", "sdg_goal_id": None,
         "translations": {
             "ru": "Существует ли значительная сезонность бизнеса?",
             "en": "Is there significant seasonality in the business?",
             "kz": "Бизнесте айқын маусымдылық бар ма?"
         }},

        {"id": 10,
         "text": "Каков уровень цифровизации бизнеса?", "sdg_goal_id": None,
         "translations": {
             "ru": "Каков уровень цифровизации бизнеса?",
             "en": "What is the level of digitalization of the business?",
             "kz": "Бизнестің цифрландыру деңгейі қандай?"
         }},
    ]

    # for q1 in questions:
    #     Question.objects.update_or_create(
    #         id=q1["id"],
    #         defaults=q1
    #     )

    # for q in questions:
    #     obj, created = Question.objects.update_or_create(
    #         id=q["id"],
    #         defaults={k: v for k, v in q.items() if k not in ("translations",)}
    #     )
    #     if "translations" in q:
    #         for lang, text in q["translations"].items():
    #             QuestionTranslation.objects.update_or_create(
    #                 question=obj,
    #                 language=lang,
    #                 defaults={"text": text}
    #             )

    for q in general_questions:
        obj, _ = GeneralQuestion.objects.update_or_create(
            id=q["id"],
            defaults={
                "text": q["text"],
                "active": True
            }
        )

        for lang, text in q["translations"].items():
            GeneralQuestionTranslation.objects.update_or_create(
                question=obj,
                language=lang,
                defaults={"text": text}
            )

    # -------------------------
    # GENERAL ANSWERS
    # -------------------------

    general_answers = [
        # Численность сотрудников
        {"id": 1, "text": "До 5 сотрудников", "question_id": 1,
         "translations": {"ru": "До 5 сотрудников", "en": "Up to 5 employees", "kz": "5 қызметкерге дейін"}},
        {"id": 2, "text": "6–10 сотрудников", "question_id": 1,
         "translations": {"ru": "6–10 сотрудников", "en": "6–10 employees", "kz": "6–10 қызметкер"}},
        {"id": 3, "text": "11–50 сотрудников", "question_id": 1,
         "translations": {"ru": "11–50 сотрудников", "en": "11–50 employees", "kz": "11–50 қызметкер"}},
        {"id": 4, "text": "51–100 сотрудников", "question_id": 1,
         "translations": {"ru": "51–100 сотрудников", "en": "51–100 employees", "kz": "51–100 қызметкер"}},
        {"id": 5, "text": "Более 100 сотрудников", "question_id": 1,
         "translations": {"ru": "Более 100 сотрудников", "en": "More than 100 employees",
                          "kz": "100-ден астам қызметкер"}},

        # Основной вид деятельности
        {"id": 6, "text": "Торговля", "question_id": 2,
         "translations": {"ru": "Торговля", "en": "Trade", "kz": "Сауда"}},
        {"id": 7, "text": "Производство", "question_id": 2,
         "translations": {"ru": "Производство", "en": "Manufacturing", "kz": "Өндіріс"}},
        {"id": 8, "text": "Сфера услуг", "question_id": 2,
         "translations": {"ru": "Сфера услуг", "en": "Services", "kz": "Қызмет көрсету саласы"}},
        {"id": 9, "text": "IT / цифровые услуги", "question_id": 2,
         "translations": {"ru": "IT / цифровые услуги", "en": "IT / digital services", "kz": "IT / цифрлық қызметтер"}},
        {"id": 10, "text": "Сельское хозяйство", "question_id": 2,
         "translations": {"ru": "Сельское хозяйство", "en": "Agriculture", "kz": "Ауыл шаруашылығы"}},


        {"id": 11, "text": "Строительство", "question_id": 2,
         "translations": {"ru": "Строительство", "en": "Construction", "kz": "Құрылыс"}},

        {"id": 12, "text": "Транспорт и логистика / складские услуги", "question_id": 2,
         "translations": {"ru": "Транспорт и логистика / складские услуги",
                          "en": "Transport and logistics / warehousing services",
                          "kz": "Көлік және логистика / қойма қызметтері"}},

        {"id": 13, "text": "Гостиничный бизнес", "question_id": 2,
         "translations": {"ru": "Гостиничный бизнес", "en": "Hospitality industry", "kz": "Қонақ үй бизнесі"}},

        {"id": 14, "text": "Туризм", "question_id": 2,
         "translations": {"ru": "Туризм", "en": "Tourism", "kz": "Туризм"}},

        {"id": 15, "text": "Финансовые и страховые услуги", "question_id": 2,
         "translations": {"ru": "Финансовые и страховые услуги",
                          "en": "Financial and insurance services",
                          "kz": "Қаржылық және сақтандыру қызметтері"}},

        {"id": 16, "text": "Недвижимость и управление имуществом", "question_id": 2,
         "translations": {"ru": "Недвижимость и управление имуществом",
                          "en": "Real estate and property management",
                          "kz": "Жылжымайтын мүлік және мүлікті басқару"}},

        {"id": 17, "text": "Профессиональные, научные и технические услуги", "question_id": 2,
         "translations": {"ru": "Профессиональные, научные и технические услуги",
                          "en": "Professional, scientific and technical services",
                          "kz": "Кәсіби, ғылыми және техникалық қызметтер"}},

        {"id": 18, "text": "Здравоохранение и социальные услуги", "question_id": 2,
         "translations": {"ru": "Здравоохранение и социальные услуги",
                          "en": "Healthcare and social services",
                          "kz": "Денсаулық сақтау және әлеуметтік қызметтер"}},

        {"id": 19, "text": "Образование, тренинги, курсы", "question_id": 2,
         "translations": {"ru": "Образование, тренинги, курсы",
                          "en": "Education, training, courses",
                          "kz": "Білім беру, тренингтер, курстар"}},

        {"id": 20, "text": "Другое", "question_id": 2,
         "translations": {"ru": "Другое", "en": "Other", "kz": "Басқа"}},

        # Организационно-правовая форма
        {"id": 21, "text": "Индивидуальный предприниматель (ИП)", "question_id": 3,
         "translations": {"ru": "Индивидуальный предприниматель (ИП)",
                          "en": "Individual entrepreneur (IE)",
                          "kz": "Жеке кәсіпкер (ЖК)"}},

        {"id": 22, "text": "Товарищество с ограниченной ответственностью (ТОО)", "question_id": 3,
         "translations": {"ru": "Товарищество с ограниченной ответственностью (ТОО)",
                          "en": "Limited liability partnership (LLP)",
                          "kz": "Жауапкершілігі шектеулі серіктестік (ЖШС)"}},

        {"id": 23, "text": "Акционерное общество (АО)", "question_id": 3,
         "translations": {"ru": "Акционерное общество (АО)",
                          "en": "Joint-stock company (JSC)",
                          "kz": "Акционерлік қоғам (АҚ)"}},

        {"id": 24, "text": "Государственное предприятие", "question_id": 3,
         "translations": {"ru": "Государственное предприятие",
                          "en": "State-owned enterprise",
                          "kz": "Мемлекеттік кәсіпорын"}},

        {"id": 25, "text": "Муниципальное предприятие", "question_id": 3,
         "translations": {"ru": "Муниципальное предприятие",
                          "en": "Municipal enterprise",
                          "kz": "Муниципалдық кәсіпорын"}},

        {"id": 26, "text": "Производственный кооператив", "question_id": 3,
         "translations": {"ru": "Производственный кооператив",
                          "en": "Production cooperative",
                          "kz": "Өндірістік кооператив"}},

        {"id": 27, "text": "Филиал иностранной компании", "question_id": 3,
         "translations": {"ru": "Филиал иностранной компании",
                          "en": "Branch of a foreign company",
                          "kz": "Шетелдік компанияның филиалы"}},

        {"id": 28, "text": "Другое", "question_id": 3,
         "translations": {"ru": "Другое", "en": "Other", "kz": "Басқа"}},

        # Производственные процессы
        {"id": 29, "text": "Да, основная деятельность — производство", "question_id": 4,
         "translations": {"ru": "Да, основная деятельность — производство",
                          "en": "Yes, the main activity is production",
                          "kz": "Иә, негізгі қызмет — өндіріс"}},

        {"id": 30, "text": "Да, вспомогательное производство", "question_id": 4,
         "translations": {"ru": "Да, вспомогательное производство",
                          "en": "Yes, auxiliary production",
                          "kz": "Иә, қосалқы өндіріс"}},

        {"id": 31, "text": "Нет, только торговля", "question_id": 4,
         "translations": {"ru": "Нет, только торговля",
                          "en": "No, only trade",
                          "kz": "Жоқ, тек сауда"}},

        {"id": 32, "text": "Нет, только услуги", "question_id": 4,
         "translations": {"ru": "Нет, только услуги",
                          "en": "No, only services",
                          "kz": "Жоқ, тек қызметтер"}},

        {"id": 33, "text": "Нет, исключительно цифровая деятельность", "question_id": 4,
         "translations": {"ru": "Нет, исключительно цифровая деятельность",
                          "en": "No, exclusively digital activity",
                          "kz": "Жоқ, тек цифрлық қызмет"}},

        # Использование ресурсов
        {"id": 34, "text": "Да, в значительных объёмах", "question_id": 5,
         "translations": {"ru": "Да, в значительных объёмах",
                          "en": "Yes, in significant volumes",
                          "kz": "Иә, айтарлықтай көлемде"}},

        {"id": 35, "text": "Да, в умеренных объёмах", "question_id": 5,
         "translations": {"ru": "Да, в умеренных объёмах",
                          "en": "Yes, in moderate volumes",
                          "kz": "Иә, орташа көлемде"}},

        {"id": 36, "text": "В ограниченных объёмах", "question_id": 5,
         "translations": {"ru": "В ограниченных объёмах",
                          "en": "In limited volumes",
                          "kz": "Шектеулі көлемде"}},

        {"id": 37, "text": "Практически не использует", "question_id": 5,
         "translations": {"ru": "Практически не использует",
                          "en": "Hardly uses",
                          "kz": "Іс жүзінде пайдаланбайды"}},

        {"id": 38, "text": "Не использует", "question_id": 5,
         "translations": {"ru": "Не использует",
                          "en": "Does not use",
                          "kz": "Пайдаланбайды"}},

        # Программы поддержки
        {"id": 39, "text": "Да, в международных", "question_id": 6,
         "translations": {"ru": "Да, в международных",
                          "en": "Yes, in international programs",
                          "kz": "Иә, халықаралық бағдарламаларда"}},

        {"id": 40, "text": "Да, в национальных", "question_id": 6,
         "translations": {"ru": "Да, в национальных",
                          "en": "Yes, in national programs",
                          "kz": "Иә, ұлттық бағдарламаларда"}},

        {"id": 41, "text": "Да, в региональных", "question_id": 6,
         "translations": {"ru": "Да, в региональных",
                          "en": "Yes, in regional programs",
                          "kz": "Иә, өңірлік бағдарламаларда"}},

        {"id": 42, "text": "Планируется участие", "question_id": 6,
         "translations": {"ru": "Планируется участие",
                          "en": "Participation is planned",
                          "kz": "Қатысу жоспарлануда"}},

        {"id": 43, "text": "Нет", "question_id": 6,
         "translations": {"ru": "Нет", "en": "No", "kz": "Жоқ"}},

        # Целевая аудитория
        {"id": 44, "text": "Физические лица (B2C)", "question_id": 7,
         "translations": {"ru": "Физические лица (B2C)", "en": "Individuals (B2C)", "kz": "Жеке тұлғалар (B2C)"}
         },
        {"id": 45, "text": "Малый и средний бизнес (B2B)", "question_id": 7,
         "translations": {"ru": "Малый и средний бизнес (B2B)", "en": "Small and medium-sized businesses (B2B)",
                          "kz": "Шағын және орта бизнес (B2B)"}
         },
        {"id": 46, "text": "Крупный бизнес", "question_id": 7,
         "translations": {"ru": "Крупный бизнес", "en": "Large enterprises", "kz": "Ірі бизнес"}
         },
        {"id": 47, "text": "Государственные организации", "question_id": 7,
         "translations": {"ru": "Государственные организации", "en": "Government organizations",
                          "kz": "Мемлекеттік ұйымдар"}
         },
        {"id": 48, "text": "Смешанная аудитория", "question_id": 7,
         "translations": {"ru": "Смешанная аудитория", "en": "Mixed audience", "kz": "Аралас аудитория"}
         },

        # Собственное помещение
        {"id": 49, "text": "Собственное производственное помещение", "question_id": 8,
         "translations": {"ru": "Собственное производственное помещение", "en": "Owned production facility",
                          "kz": "Жеке өндірістік ғимарат"}
         },
        {"id": 50, "text": "Собственный офис", "question_id": 8,
         "translations": {"ru": "Собственный офис", "en": "Owned office", "kz": "Жеке кеңсе"}
         },
        {"id": 51, "text": "Аренда производственного помещения", "question_id": 8,
         "translations": {"ru": "Аренда производственного помещения", "en": "Rented production facility",
                          "kz": "Өндірістік ғимаратты жалға алу"}
         },
        {"id": 52, "text": "Аренда офиса", "question_id": 8,
         "translations": {"ru": "Аренда офиса", "en": "Rented office", "kz": "Кеңсені жалға алу"}
         },
        {"id": 53, "text": "Работа полностью онлайн", "question_id": 8,
         "translations": {"ru": "Работа полностью онлайн", "en": "Fully online operation",
                          "kz": "Толығымен онлайн жұмыс"}
         },

        # Сезонность
        {"id": 54, "text": "Да, ярко выраженная сезонность", "question_id": 9,
         "translations": {"ru": "Да, ярко выраженная сезонность", "en": "Yes, strongly seasonal",
                          "kz": "Иә, айқын маусымдылық бар"}
         },
        {"id": 55, "text": "Умеренная сезонность", "question_id": 9,
         "translations": {"ru": "Умеренная сезонность", "en": "Moderate seasonality", "kz": "Орташа маусымдылық"}
         },
        {"id": 56, "text": "Незначительная сезонность", "question_id": 9,
         "translations": {"ru": "Незначительная сезонность", "en": "Low seasonality", "kz": "Төмен маусымдылық"}
         },
        {"id": 57, "text": "Бизнес работает круглый год", "question_id": 9,
         "translations": {"ru": "Бизнес работает круглый год", "en": "Operates year-round",
                          "kz": "Жыл бойы жұмыс істейді"}
         },
        {"id": 58, "text": "Затрудняюсь ответить", "question_id": 9,
         "translations": {"ru": "Затрудняюсь ответить", "en": "Difficult to answer", "kz": "Жауап беру қиын"}
         },

        # Уровень цифровизации
        {"id": 59, "text": "Полностью цифровой", "question_id": 10,
         "translations": {"ru": "Полностью цифровой", "en": "Fully digital", "kz": "Толығымен цифрлық"}
         },
        {"id": 60, "text": "Частично цифровой", "question_id": 10,
         "translations": {"ru": "Частично цифровой", "en": "Partially digital", "kz": "Ішінара цифрлық"}
         },
        {"id": 61, "text": "Традиционный бизнес с отдельными цифровыми процессами", "question_id": 10,
         "translations": {"ru": "Традиционный бизнес с отдельными цифровыми процессами",
                          "en": "Traditional business with some digital processes",
                          "kz": "Жекелеген цифрлық процестері бар дәстүрлі бизнес"}
         },
        {"id": 62, "text": "Полностью офлайн", "question_id": 10,
         "translations": {"ru": "Полностью офлайн", "en": "Fully offline", "kz": "Толығымен офлайн"}
         },
        {"id": 63, "text": "Затрудняюсь ответить", "question_id": 10,
         "translations": {"ru": "Затрудняюсь ответить", "en": "Difficult to answer", "kz": "Жауап беру қиын"}
         },
    ]

    # for a in general_answers:
    #     AnswerOption.objects.update_or_create(
    #         id=a["id"],
    #         defaults=a
    #     )

    for ao in general_answers:
        obj, created = AnswerOption.objects.update_or_create(
            id=ao["id"],
            defaults={
                "text": ao["text"],
                "question_id": ao["question_id"]
            }
        )

        if "translations" in ao:
            for lang, text in ao["translations"].items():
                AnswerOptionTranslation.objects.update_or_create(
                    answer_option=obj,
                    language=lang,
                    defaults={"text": text}
                )


def reverse_seed_data(apps, schema_editor):

    SDGGoal = apps.get_model('portal', 'SDGGoal')
    SDGQuestion = apps.get_model('portal', 'SDGQuestion')
    GeneralQuestion = apps.get_model('portal', 'GeneralQuestion')
    AnswerOption = apps.get_model('portal', 'AnswerOption')
    AnswerOptionTranslation = apps.get_model('portal', 'AnswerOptionTranslation')
    SDGQuestionTranslation = apps.get_model('portal', 'SDGQuestionTranslation')
    GeneralQuestionTranslation = apps.get_model('portal', 'GeneralQuestionTranslation')


    # Удаляем переводы
    AnswerOptionTranslation.objects.all().delete()
    SDGQuestionTranslation.objects.all().delete()
    GeneralQuestionTranslation.objects.all().delete()

    # -------------------------
    # Удаляем вопросы
    # -------------------------
    SDGQuestion.objects.filter(
        id__in=range(1, 80)
    ).delete()

    GeneralQuestion.objects.filter(
        id__in=range(1, 20)
    ).delete()

    # -------------------------
    # Удаляем ответы
    # -------------------------
    AnswerOption.objects.filter(
        id__in=range(1, 80)
    ).delete()

    # -------------------------
    # Удаляем SDG цели
    # -------------------------
    SDGGoal.objects.filter(id__in=range(1, 15)).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_survey_tables'),
    ]

    operations = [
        migrations.RunPython(seed_data, reverse_seed_data),
    ]
