spring.application.name=diplom
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
mailing.users.api-key=${MAILING_USERS_API_KEY}
mailing.users.url=${MAILING_USERS_URL}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
server.port=8089
