spring.datasource.url=jdbc:mysql://mysql:3306/business_sustainability?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.http.encoding.enabled=true
spring.http.encoding.charset=UTF-8
spring.http.encoding.force=true

spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
openai.api-key={AI_KEY}
openai.model={AI_MODEL}
openai.url=https://api.openai.com/v1/chat/completions

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true