spring.datasource.url=jdbc:mysql://mysql:3306/business_sustainability?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.http.encoding.enabled=true
spring.http.encoding.charset=UTF-8
spring.http.encoding.force=true
spring.jpa.defer-datasource-initialization=true
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.initialization-fail-timeout=60000
spring.datasource.hikari.maximum-pool-size=10

yandex.translate.url={YANDEX_TRANSLATE_URL}
yandex.translate.folder-id={YANDEX_TRANSLATE_FOLDER_ID}
yandex.translate.api-key={YANDEX_TRANSLATE_API_KEY}

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true