services:
  mysql:
    image: mysql:8.0
    container_name: business_mysql
    environment:
      MYSQL_DATABASE: business_sustainability
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 20

  app:
    image: chilivardev/analytics-service:latest
    container_name: analytics_service
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/business_sustainability?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      AI_KEY: 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
      AI_MODEL: gpt-4.1-mini
      AI_URL: https://api.openai.com/v1/chat/completions

volumes:
  mysql_data:
